fix webhook create script

diff --git a/charts/prow/templates/github_hooks_install.yaml b/charts/prow/templates/github_hooks_install.yaml
--- a/charts/prow/templates/github_hooks_install.yaml
+++ b/charts/prow/templates/github_hooks_install.yaml
@@ -31,7 +31,7 @@ spec:
         - name: HOOK_URL
           value: "{{ .Values.githubHookConsumerAddress }}"
         - name: REPOS_TO_HOOK
-          value: "( {{ .Values.repos }} )"
+          value: "{{ .Values.repos }}"
         - name: AUTH_TOKEN
           valueFrom:
             secretKeyRef:
@@ -41,16 +41,24 @@ spec:
           value: &script |-
             HMAC_KEY=`/hook_manager create_hmac` #used by the webhook security
             echo $HMAC_KEY >hmac
-            kubectl create secret generic hmac --from-file=./hmac
-            rm -f ./created_hooks
-            for repo in "${REPOS_TO_HOOK[@]}"
+            #kubectl create secret generic hmac --from-file=./hmac
+            echo
+            REPOS=(`echo ${REPOS_TO_HOOK} | sed -e 's/\[//g;s/\]//g;s/(//g;s/)//g;' | tr -d '\n\r'`)
+            mkdir -p /etc/webhooks
+            touch /etc/webhooks/created_hooks
+            for repo in "${REPOS[@]}"
             do
               echo "creating hook for repo: ${repo}"
               HOOK_ID=`/hook_manager create_webhook --credentials=${BOT_USER_ID}:${AUTH_TOKEN} --url=${HOOK_URL} --repo=${repo}`
-              echo "${HOOK_ID}:${repo}" >> created_hooks
+              if [ $? -eq 0 ]
+              then 
+                echo "${HOOK_ID}:${repo}" >> /etc/webhooks/created_hooks
+              else 
+                echo "invalid repo: ${repo}"
+              fi
             done
             kubectl delete secret created-hooks
-            kubectl create secret generic created-hooks --from-file=./created_hooks
+            kubectl create secret generic created-hooks --from-file=/etc/webhooks/created_hooks
         command: ["bash"]
         args: ["-c", *script]
       
